<?php
require_once('library.php');
$active3 = 'active';
$title = 'Services | We provide the first-class solar energy solutions to families and businesses across the - ' . $siteName;
require_once('head.php'); ?>

<body>
  <div class="ie-panel"><a href="http://windows.microsoft.com/en-US/internet-explorer/"><img src="images/ie8-panel/warning_bar_0000_us.jpg" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
  <div class="preloader">
    <div class="preloader-body">
      <div class="cssload-container">
        <div class="cssload-speeding-wheel"></div>
      </div>
    </div>
  </div>
  <div class="page">
    <!-- Header-->
    <?php require_once('header.php'); ?>
    <!-- Breadcrumbs-->
    <div class="breadcrumbs-custom bg-white">
      <div class="container">
        <ul class="breadcrumbs-custom-path">
          <li><a href="./">Home</a></li>
          <li class="active">Services</li>
        </ul>
      </div>
    </div>
    <section class="section section-md bg-white">
      <div class="container">
        <div class="row">
          <div class="col-xl-8 col-md-10">
            <h1>Services that We Provide</h1>
            <div style="display: none;" class="row row-30 offset-md">
              <div class="col-sm-6">
                <p>Lectus diam, massa vulputate tellus fames senectus. Risus ut at orci, egestas turpis. Egestas nascetur ornare odio eu libero condimentum in congue.</p>
              </div>
              <div class="col-sm-6">
                <p>Sit luctus quis amet sit tincidunt dis. Non massa imperdiet vulputate lobortis tincidunt. Nunc amet bibendum erat.</p>
              </div>
            </div>
          </div>
        </div>

        <div class="row row-30">
          <div class="col-xl-3 col-lg-4 col-sm-6">
            <div class="service">
              <div class="service-icon">
                <!-- <svg class="icon-svg-stroke" width="33" height="32" viewBox="0 0 33 32" fill="none">
                  <path d="M4 17V29H8V22H12V29H28V17" stroke-width="2" />
                  <path d="M1 14.5L9 4M9 4L17 14H30L22 4H9Z" stroke-width="2" />
                </svg> -->
                <img src="img/photo42.jpg" alt width="460" height="560" loading="lazy">
              </div>
              <p class="service-text">1. Solar Panel Installation:</p>
              <div class="service-link h4"><a href="services">
                  We specialize in the design and installation of solar panel systems for residential, commercial, and industrial applications. Whether you're looking to power your home, business, or community with solar energy, we have the expertise to bring your vision to life.</a></div>
            </div>
          </div>
          <div class="col-xl-3 col-lg-4 col-sm-6">
            <div class="service">
              <div class="service-icon">
                <!-- <svg class="icon-svg-stroke" width="32" height="32" viewBox="0 0 32 32" fill="none">
                  <rect x="6" y="6" width="20" height="25" rx="3" stroke-width="2" />
                  <rect x="10" y="15" width="12" height="4" stroke-width="2" />
                  <rect x="10" y="23" width="12" height="4" stroke-width="2" />
                  <path d="M12 3V1H20V3" stroke-width="2" stroke-linejoin="round" />
                </svg> --><img src="img/photo43.jpg" alt width="460" height="560" loading="lazy">
              </div>
              <p class="service-text">2. Wind Turbine Installation:</p>
              <div class="service-link h4"><a href="services">
                  Harness the power of wind with our expert wind turbine installation services. From single turbines to large-scale wind farms, we have the know-how to optimize energy production and drive your sustainability goals.</a></div>
            </div>
          </div>
          <div class="col-xl-3 col-lg-4 col-sm-6">
            <div class="service">
              <div class="service-icon">
                <!-- <svg class="icon-svg-stroke" width="32" height="32" viewBox="0 0 32 32" fill="none">
                  <path d="M10 17.5882L17 7V13.3529H22L15 25V17.5882H10Z" stroke-width="2" />
                  <path d="M26 12C26 12 27 14 27 16C27 18 26 20 26 20" stroke-width="2" />
                  <path d="M6 12C6 12 5 14 5 16C5 18 6 20 6 20" stroke-width="2" />
                  <path d="M29 8C29 8 31 10.6667 31 16C31 21.3333 29 24 29 24" stroke-width="2" />
                  <path d="M3 8C3 8 1 10.6667 1 16C1 21.3333 3 24 3 24" stroke-width="2" />
                </svg> --><img src="img/photo44.jpg" alt width="460" height="560" loading="lazy">
              </div>
              <p class="service-text">3. Energy Storage Solutions:</p>
              <div class="service-link h4"><a href="services">
                  To maximize energy independence and resilience, we offer state-of-the-art energy storage solutions that store excess electricity generated by your solar panels or wind turbines for use during periods of low energy production.</a></div>
            </div>
          </div>
          <div class="col-xl-3 col-lg-4 col-sm-6">
            <div class="service">
              <div class="service-icon">
                <!-- <svg class="icon-svg-stroke" width="32" height="32" viewBox="0 0 32 32" fill="none">
                  <path d="M3.95783 11.2873L6.74403 2H16H25.256L28.0422 11.2873L30.656 20H16H1.34403L3.95783 11.2873Z" stroke-width="2" />
                  <path d="M16 24V30M16 30H10M16 30H22" stroke-width="2" />
                </svg> -->
                <img src="img/photo45.jpg" alt width="460" height="560" loading="lazy">
              </div>
              <p class="service-text">4. Maintenance and Support:</p>
              <div class="service-link h4"><a href="services">
                  Our commitment to your renewable energy journey doesn't end with installation. We provide ongoing maintenance and support services to ensure your system operates efficiently and reliably for years to come.</a></div>
            </div>
          </div>
        </div>

      </div>
    </section>

    <section class="section bg-dark bg-image" style="background-image: url(images/services-01-1920x1445.jpg)">
      <div class="section-lg">
        <div class="container">
          <div class="row">
            <div class="col-xl-8 col-md-10">
              <h2>We Provide Solar Energy All Over the US</h2>
              <div class="row row-30 offset-sm">
                <div class="col-sm-6">
                  <p>Join Us in Embracing a Brighter Future:
                    At <?php print $siteName; ?>, we believe in the power of collaboration and shared responsibility. By choosing us as your renewable energy partner, you contribute to a sustainable future while enjoying the many benefits of clean energy.</p>
                </div>
                <div class="col-sm-6">
                  <p>Contact us today to explore how we can tailor a solar and wind energy solution that meets your needs, saves you money, and contributes to a healthier planet.</p>
                  <p>Together, let's make a positive impact one solar panel and wind turbine at a time</p>
                </div>
              </div>
            </div>
          </div>
          <div class="row offset-lg">
            <div class="col-lg-3 col-sm-6">
              <!--Counter-->
              <div class="box-counter">
                <div class="box-counter-main">
                  <div class="counter">135</div>
                  <div class="counter-postfix">MW</div>
                </div>
                <p class="box-counter-title">Capacity developed</p>
              </div>
            </div>
            <div class="col-lg-3 col-sm-6">
              <!--Counter-->
              <div class="box-counter">
                <div class="box-counter-main">
                  <div class="counter">127</div>
                  <div class="counter-postfix">k</div>
                </div>
                <p class="box-counter-title">Metric Tons of CO2</p>
              </div>
            </div>
            <div style="display: none;" class="col-lg-3 col-sm-6">
              <!--Counter-->
              <div class="box-counter">
                <div class="box-counter-main">
                  <div class="counter">27</div>
                  <div class="counter-postfix">k</div>
                </div>
                <p class="box-counter-title">Cars off the road</p>
              </div>
            </div>
            <div style="display: none;" class="col-lg-3 col-sm-6">
              <!--Counter-->
              <div class="box-counter">
                <div class="box-counter-main">
                  <div class="counter disabled">2.1</div>
                  <div class="counter-postfix">M</div>
                </div>
                <p class="box-counter-title">Trees Planted</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div style="display: none;" class="section-lg pt-0">
        <div class="container">
          <div class="row">
            <div class="col-xl-6 col-lg-8 col-md-10">
              <h3>Development Partners</h3>
              <p>Condimentum metus ac neque varius ullamcorper netus suspendisse. Aliquet lectus amet vitae risus phasellus. Semper sed eu, quam integer. Ultrices amet proin sit hac mauris.</p>
              <!-- Owl Carousel-->
              <div class="owl-carousel offset-md" data-items="2" data-sm-items="3" data-owl="{&quot;autoplayTimeout&quot;:3500}">
                <div class="partner"><a href="#"><img src="images/partner-light-01-160x80.png" alt="" width="160" height="80" loading="lazy" /></a></div>
                <div class="partner"><a href="#"><img src="images/partner-light-02-160x80.png" alt="" width="160" height="80" loading="lazy" /></a></div>
                <div class="partner"><a href="#"><img src="images/partner-light-03-160x80.png" alt="" width="160" height="80" loading="lazy" /></a></div>
                <div class="partner"><a href="#"><img src="images/partner-light-04-160x80.png" alt="" width="160" height="80" loading="lazy" /></a></div>
                <div class="partner"><a href="#"><img src="images/partner-light-05-160x80.png" alt="" width="160" height="80" loading="lazy" /></a></div>
                <div class="partner"><a href="#"><img src="images/partner-light-06-160x80.png" alt="" width="160" height="80" loading="lazy" /></a></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Solar Plans that Fit Your Needs-->
    <section class="section section-md bg-image" style="background-image: url(images/bg-img-02-1920x600.jpg)">
      <div class="container">
        <div class="row row-30">
          <div class="col-md-7 wow fadeInLeft">
            <h2>Solar Plans that Fit Your Needs</h2>
          </div>
          <div class="col-md-5 wow fadeInRight">
            <p>Looking forward to power your home with solar energy? Call us and we'll help you find the right pricing plan that meets your needs.</p>
            <div class="offset-40"><a class="btn btn-white" href="tel:<?php print $sitePhone; ?>"><?php print $sitePhone; ?></a></div>
          </div>
        </div>
      </div>
    </section>

    <!-- Advantages-->
    <section class="section section-md bg-white">
      <div class="container">
        <div class="row row-40 row-xl-60 justify-content-center">
          <div class="col-xl-8 col-md-10 wow fadeInUp">
            <h3 class="text-center">Why You Should Choose Solar Iron Solar Energy Out of Other Companies</h3>
          </div>
          <div class="col-xl-10 wow fadeInUp">
            <div class="row row-30">
              <div class="col-md-3">
                <div class="advantage">
                  <div class="advantage-icon">
                    <svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <rect x="1" y="8" width="25" height="26" fill="#FBE547" stroke="#15171A" stroke-width="2"></rect>
                      <path d="M26 13H37.5251L47 22.416V34H26V13Z" stroke="#15171A" stroke-width="2"></path>
                      <rect x="7" y="30" width="10" height="10" rx="5" fill="white" stroke="#15171A" stroke-width="2"></rect>
                      <rect x="31" y="30" width="10" height="10" rx="5" fill="white" stroke="#15171A" stroke-width="2"></rect>
                    </svg>
                  </div>
                  <p class="advantage-text">Fastest delivery in the United States</p>
                </div>
              </div>
              <div class="col-md-3">
                <div class="advantage">
                  <div class="advantage-icon">
                    <svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M3 12L23 20.9999V45.9999L3 36.9999V12Z" fill="#FBE547"></path>
                      <path d="M45 12L24 21.0219V46L45 37.0079V12Z" fill="#FBE547"></path>
                      <path d="M3 12.3529V36.9412L23.2759 46M3 12.3529L23.2759 21.4118M3 12.3529L13.1379 7.17647M23.2759 46V21.4118M23.2759 46L45 36.9412V12.3529M23.2759 21.4118L34.1379 16.8824M45 12.3529L23.2759 2L13.1379 7.17647M45 12.3529L34.1379 16.8824M34.1379 16.8824L13.1379 7.17647M34.1379 16.8824V27.9286" stroke="#15171A" stroke-width="2"></path>
                    </svg>
                  </div>
                  <p class="advantage-text">Best conditions for equipment storage</p>
                </div>
              </div>
              <div class="col-md-3">
                <div class="advantage">
                  <div class="advantage-icon">
                    <svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <mask id="path-1-inside-1" fill="white">
                        <path d="M7 27H24H41V31C41 40.3888 33.3888 48 24 48C14.6112 48 7 40.3888 7 31V27Z"></path>
                      </mask>
                      <path d="M24 36H23V37H24V36ZM27 37C27.5523 37 28 36.5523 28 36C28 35.4477 27.5523 35 27 35V37ZM23 27V36H25V27H23ZM24 37H27V35H24V37ZM7 27V25H5V27H7ZM41 27H43V25H41V27ZM39 27V31H43V27H39ZM9 31V27H5V31H9ZM7 29H24V25H7V29ZM24 29H41V25H24V29ZM24 46C15.7157 46 9 39.2843 9 31H5C5 41.4934 13.5066 50 24 50V46ZM39 31C39 39.2843 32.2843 46 24 46V50C34.4934 50 43 41.4934 43 31H39Z" fill="#15171A" mask="url(#path-1-inside-1)"></path>
                      <rect x="2" y="20" width="44" height="8" rx="3" fill="#FBE547" stroke="#15171A" stroke-width="2"></rect>
                      <path d="M8 16C8 11.0294 12.0294 7 17 7H31C35.9706 7 40 11.0294 40 16V20H8V16Z" fill="#FBE547" stroke="#15171A" stroke-width="2"></path>
                      <path d="M20 4C20 2.34315 21.3431 1 23 1H25C26.6569 1 28 2.34315 28 4V20H20V4Z" fill="white" stroke="#15171A" stroke-width="2"></path>
                    </svg>
                  </div>
                  <p class="advantage-text">The best team of professionals</p>
                </div>
              </div>
              <div class="col-md-3">
                <div class="advantage">
                  <div class="advantage-icon">
                    <svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <rect x="1" y="1" width="46" height="46" rx="23" stroke="#15171A" stroke-width="2"></rect>
                      <line x1="24" y1="1" x2="24" y2="47" stroke="#15171A" stroke-width="2"></line>
                      <path d="M24 1C24 1 11 6.36667 11 24C11 41.6333 24 47 24 47" stroke="#15171A" stroke-width="2"></path>
                      <path d="M24 1C24 1 37 6.36667 37 24C37 41.6333 24 47 24 47" stroke="#15171A" stroke-width="2"></path>
                      <circle cx="36" cy="16" r="5" fill="#FBE547" stroke="#15171A" stroke-width="2"></circle>
                      <circle cx="9" cy="35" r="8" fill="#FBE547" stroke="#15171A" stroke-width="2"></circle>
                    </svg>
                  </div>
                  <p class="advantage-text">Extensive work <br class="d-none d-xl-block"> experience</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <div class="section-divider">
      <div class="container">
        <hr />
      </div>
    </div>

    <section style="display: none;" class="section section-lg bg-white">
      <div class="container">
        <h5>Featured Resources</h5>
        <div class="row row-40 justify-content-between offset-md">
          <div class="col-md-6">
            <h2>Learn More About Solar Energy Development</h2>
            <p>Amet aenean placerat aenean aliquet quis facilisis. <br class="d-none d-xl-block"> Ipsum massa amet amet sit lacus. Senectus nullam <br class="d-none d-xl-block"> fringilla habitant mattis orci sapien quis urna.</p><a class="btn btn-primary" href="grid-shop.html">Make Request</a>
          </div>
          <div class="col-xl-5 col-md-6">
            <div class="row row-40 row-xl-60">
              <div class="col-md-12 col-sm-6">
                <div class="unit">
                  <div class="unit-left">
                    <div class="icon-circle bg-light">
                      <svg class="icon-svg" width="24" height="22" viewBox="0 0 24 22" fill="none">
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M4.63931 9.6897C3.18166 9.6897 2 10.8714 2 12.329V20H5.86667V15.9311H7.86667V22H0V12.329C0 9.76679 2.07709 7.6897 4.63931 7.6897C5.8596 7.6897 7.03074 8.17048 7.89904 9.02789L11.9693 13.0471L10.564 14.4702L6.49378 10.451C5.9998 9.96322 5.33353 9.6897 4.63931 9.6897Z"></path>
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M19.3607 9.6897C20.8183 9.6897 22 10.8714 22 12.329V20H18.1333V15.9311H16.1333V22H24V12.329C24 9.76679 21.9229 7.6897 19.3607 7.6897C18.1404 7.6897 16.9693 8.17048 16.101 9.02789L12.764 12.323L14.1693 13.7461L17.5062 10.451C18.0002 9.96322 18.6665 9.6897 19.3607 9.6897Z"></path>
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M4.3 4.51724C5.04184 4.51724 5.6 3.93002 5.6 3.25862C5.6 2.58722 5.04184 2 4.3 2C3.55816 2 3 2.58722 3 3.25862C3 3.93002 3.55816 4.51724 4.3 4.51724ZM4.3 6.51724C6.12254 6.51724 7.6 5.05831 7.6 3.25862C7.6 1.45893 6.12254 0 4.3 0C2.47746 0 1 1.45893 1 3.25862C1 5.05831 2.47746 6.51724 4.3 6.51724Z"></path>
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M19.7004 4.51724C20.4422 4.51724 21.0004 3.93002 21.0004 3.25862C21.0004 2.58722 20.4422 2 19.7004 2C18.9586 2 18.4004 2.58722 18.4004 3.25862C18.4004 3.93002 18.9586 4.51724 19.7004 4.51724ZM19.7004 6.51724C21.5229 6.51724 23.0004 5.05831 23.0004 3.25862C23.0004 1.45893 21.5229 0 19.7004 0C17.8779 0 16.4004 1.45893 16.4004 3.25862C16.4004 5.05831 17.8779 6.51724 19.7004 6.51724Z"></path>
                      </svg>
                    </div>
                  </div>
                  <div class="unit-body">
                    <h4 class="unit-title">Affordable Pricing Policy</h4>
                    <p class="unit-text">Sem malesuada in at vitae pulvinar amet a sed. Diam imperdiet convallis ipsum nibh condimentum pellentesque senectus potenti. Consectetur viverra.</p>
                  </div>
                </div>
              </div>
              <div class="col-md-12 col-sm-6">
                <div class="unit">
                  <div class="unit-left">
                    <div class="icon-circle bg-light">
                      <svg class="icon-svg" width="24" height="20" viewBox="0 0 24 20" fill="none">
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M15 0L24 13H9L0 0H15ZM3.81714 2L6.24021 5.5H10.0914L7.66835 2H3.81714ZM10.1009 2L12.524 5.5H16.3752L13.9521 2H10.1009ZM17.7598 7.5H13.9086L16.3316 11H20.1829L17.7598 7.5ZM13.8991 11L11.476 7.5H7.62483L10.0479 11H13.8991Z"></path>
                        <path d="M1 6V20H8V18H3V6H1Z"></path>
                        <path d="M18 14V20H23V18H20V14H18Z"></path>
                      </svg>
                    </div>
                  </div>
                  <div class="unit-body">
                    <h4 class="unit-title">Superior Solutions</h4>
                    <p class="unit-text">Faucibus velit etiam feugiat sociis habitant. Hendrerit vivamus tellus aliquet vitae sit venenatis cras. Vitae habitasse maecenas nulla id massa.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Footer-->
    <?php require_once('footer.php'); ?>